[project]
name = "sound-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.124.2",
    "gpiozero>=2.0.1",
    "rpi-gpio>=0.7.1",
    "uvicorn>=0.38.0",
]
